"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.app = void 0;
const express_1 = __importDefault(require("express"));
const morgan_1 = __importDefault(require("morgan"));
const cors_1 = __importDefault(require("cors"));
const dotenv_1 = __importDefault(require("dotenv"));
dotenv_1.default.config();
const _errorHandler_1 = require("./middlewares/_errorHandler");
const _home_1 = require("./routes/_home");
const _pusherAuth_1 = require("./routes/_pusherAuth");
const _errors_1 = require("./helpers/_errors");
exports.app = (0, express_1.default)();
exports.app.use((0, cors_1.default)());
exports.app.use(express_1.default.json());
exports.app.set("port", process.env.PORT || 5001);
exports.app.use((0, morgan_1.default)("dev"));
exports.app.use("/", _home_1.homeRoute);
exports.app.use("/pusher/auth", _pusherAuth_1.pusherAuthRoute);
exports.app.use(_errorHandler_1._errorHandler);
(0, _errors_1.handleUncaughtErrors)();
